version: '3.8'

services:
  # 1. PHP Web Application (Frontend/Backend inside the container)
  web:
    build: .
    ports:
      - "8081:80"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=bala@2701
      - DB_NAME=hepl_payroll

  # 2. phpMyAdmin UI (Connects to your external Windows DB)
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8888:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: root
      PMA_PASSWORD: bala@2701
